name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI

on: [push, pull_request]

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    # # remote debugging
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: check git info
      run: |
        git tag -l
        git status
        git describe --tags --dirty --match "2[0-9]*"

    # - name: test and build
    #   run: |
    #     pip install pandas wheel pytest tables build
    #     make test
    #     make wheel

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.9.0
      # env:
        # SETUPTOOLS_ENABLE_FEATURES: legacy-editable
      with:
        package-dir: ./src/supy
        output-dir: wheelhouse
        config-file: ./src/supy/pyproject.toml

    - name: Publish distribution ğŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        packages_dir: wheelhouse
        verbose: true
        skip_existing: true
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution ğŸ“¦ to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        packages_dir: wheelhouse
        verbose: true
        skip_existing: true
        password: ${{ secrets.PYPI_API_TOKEN }}
